apiVersion: v1
kind: Namespace
metadata:
  name: bluemap
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redcraft-bluemap
  namespace: bluemap
spec:
  dnsNames:
    - map.redcraft.org
  secretName: bluemap-certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redcraft-bluemap
  namespace: bluemap
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - map.redcraft.org
      secretName: bluemap-certificate
  rules:
    - host: map.redcraft.org
      http:
        paths:
          - backend:
              service:
                name: bluemap
                port:
                  number: 80
            pathType: ImplementationSpecific
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: bluemap
  namespace: bluemap
spec:
  ports:
    - name: bluemap
      port: 80
      protocol: TCP
      targetPort: 8804
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: bluemap
  namespace: bluemap
subsets:
  - addresses:
      - ip: 195.201.181.21
    ports:
      - name: bluemap
        port: 8100
        protocol: TCP
