apiVersion: v1
kind: Namespace
metadata:
  name: plan
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redcraft-plan
  namespace: plan
spec:
  ingressClassName: nginx
  rules:
    - host: plan.redcraft.org
      http:
        paths:
          - backend:
              service:
                name: plan
                port:
                  number: 80
            pathType: ImplementationSpecific
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: plan
  namespace: plan
spec:
  ports:
    - name: plan
      port: 80
      protocol: TCP
      targetPort: 8804
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: plan
  namespace: plan
subsets:
  - addresses:
      - ip: 10.0.2.143
    ports:
      - name: plan
        port: 8804
        protocol: TCP
