apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redcraft-website
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: redcraft.org
      http:
        paths:
          - backend:
              service:
                name: website
                port:
                  number: 80
            pathType: ImplementationSpecific
            path: /