apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redcraft-website
  namespace: staging
spec:
  dnsNames:
    - staging.redcraft.org
  secretName: website-certificate
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redcraft-website
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - staging.redcraft.org
      secretName: website-certificate
  rules:
    - host: staging.redcraft.org
      http:
        paths:
          - backend:
              service:
                name: website
                port:
                  number: 80
            pathType: ImplementationSpecific
            path: /