apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redcraft-website
  namespace: staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - staging.redcraft.org
      secretName: website-certificate
  rules:
    - host: staging.redcraft.org
      http:
        paths:
          - backend:
              service:
                name: website
                port:
                  number: 80
            pathType: ImplementationSpecific
            path: /
