<?php

return [
    "title" => "About and FAQ",

    "about" => [
        "title" => "About",
        "1" => "RedCraft.org is a non-profit Minecraft server infrastructure opened in 2022.",
        "2" => "Born from the merging of TopRed.fr and KingdomHills.fr, the RedCraft project aims to bring together communities of Minecraft players regardless of their origin. Thanks to a real time translation system, language barriers fall and leave room for a united community.",
        "3" => [
            "1" => "The entire RedCraft.org project is developed with modern tools in order to have a flexible infrastructure, while being open source. Find all the sources on our ",
            "2" => "GitHub",
            "3" => " page!",
        ],
        "4" => [
            "1" => "Respect, having fun, and helping each other.",
            "2" => "This is our credo, which guarantees a place of learning, fun and good living.",
        ]
    ],

    "faq" => [
        "title" => "FAQ",
        "1" => [
            "title" => "What is RedCraft.org?",
            "description" => "RedCraft.org is a multilingual Minecraft server infrastructure. The project gathers several creative or survival servers, the whole being completely open source!",
        ],
        "2" => [
            "title" => "How does the project work?",
            "description" => [
                "1" => "The entire RedCraft.org project is ",
                "2" => "open source",
                "3" => ". This means that the entire project was created for no profit, no one makes money on the project! Besides, ",
                "4" => "one of the main goals of RedCraft.org is to be self-sufficient",
                "5" => ". The money generated by the project goes only for its improvement.",
            ]
        ],
        "3" => [
            "title" => "How to help the project?",
            "description" => [
                "1" => "The most effective way to contribute to the project is to come and talk to us! Are you interested in writing code, helping build the field or participating in the organization? Get in touch with us, either via the ",
                "2" => "contact form",
                "3" => ", via ",
                "4" => "the Discord",
                "5" => " or directly in game.",
            ]
        ],
        "4" => [
            "title" => "What version does the server support?",
            "description" => [
                "1" => "LThe server is accessible from version ",
                "2" => " to version ",
                "3" => ".",
            ]
        ],
        "5" => [
            "title" => "How to join the server on Minecraft Bedrock Edition?",
            "description" => "Support for the Bedrock version will arrive with the release of the server beta.",
            // "description" => "Players on Bedrock version are not skimped! To join RedCraft.org, you need a Java account. When you log in to the server, you will be asked for your Java account information. Fill out the form and you're ready to join us in game.",
        ],
    ],

    "licenses" => [
        "title" => "Licenses and sources",
        "1" => [
            "title" => "Website",
            "website" => "Website",
            "and" => " and ",
            "license" => "License",
            "description" => [
                "laravel" => " : An open-source web framework written in PHP respecting the model-view-controller principle and entirely developed in object-oriented programming.",
                "livewire" => " : A full-stack framework for Laravel that simplifies the creation of dynamic interfaces, without leaving the comfort of Laravel.",
                "tailwind" => " : A utility-oriented CSS framework, full of classes that can be composed to build any design, directly in your code.",
                "alpine" => " : A robust and minimal framework to compose JavaScript behavior in your code.",
                "sass" => " : A preprocessor scripting language that is compiled or interpreted into CSS.",
                "fontawesome" => " : Font and icon tool based on CSS, LESS and SASS.",
            ]
        ]
    ]
];
