name: Test project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE redcraft' -uroot -proot

      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          tools: composer:v2
          extensions: sqlite3

      - name: Update dependencies
        run: composer update

      - name: Install dependencies
        run: composer install

      - name: Use default .env
        run: cp .env.testing .env

      - name: clear cache
        run: php artisan config:clear

      - name: Generate key
        run: php artisan key:generate

      - name: Apply migrations on local database
        run: php artisan migrate

      - name: Run tests
        run: |
          cp .env .env.testing
          php artisan test
